# Generated by Django 4.2.4 on 2023-08-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
    ]
