# Generated by Django 4.2.4 on 2023-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_branch_options_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.CharField(default='cse', max_length=20),
            preserve_default=False,
        ),
    ]
